# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f594cf08fcc43dbea990c2544d6bc5c0560f865c42f3ef30b3006aa77cabef8c8fa7b36f6b50afbc843d234d7abdbeb7e297a3f2017f165d6113499955c2a58

test:
  secret_key_base: b75b1e85a13811b7b797537c92f3747a151981cfd43c58d79150e106def8c39a456c72eeceb1d692815924f2727f5172b0886d5ebf88cc5272a159875bb5c47f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
